sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
addons:
  firefox: "55.0"
env:
#- TEST_SUITE="{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'iPhone'}"
#- TEST_SUITE="{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'iPad'}"
- TEST_SUITE="{'browsers':['PhantomJS'],'runNegTests':true,'runSimpleTests':true}"
- TEST_SUITE="{'browsers':['Chrome'],'runNegTests':false,'runSimpleTests':false}"
- TEST_SUITE="{'browsers':['Marionette'],'runNegTests':false,'runSimpleTests':false}"
- TEST_SUITE="{'browsers':['Opera'],'runNegTests':false,'runSimpleTests':false}"
- TEST_SUITE="{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Desktop'}"
- TEST_SUITE="{'browsers':['BrowserStack'],'runNegTests':false,'runSimpleTests':false,'groupName':'Android'}"
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- wget https://s3.amazonaws.com/iridium-cloud-support/opera-developer_48.0.2670.0_amd64.deb
- sudo dpkg -i opera-developer*.deb
- wget ${GPG_Keyring}
- openssl aes-256-cbc -K $encrypted_a39daf039737_key -iv $encrypted_a39daf039737_iv -in iridium_github_pages.enc -out iridium_github_pages -d
- chmod 600 iridium_github_pages
- eval `ssh-agent -s`
- ssh-add iridium_github_pages
- rm -f iridium_github_pages
script: ./gradlew -DtestBrowsers=${TEST_SUITE} check --stacktrace
deploy:
  - provider: script
    script: travis_publish.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: travis_publishdocs.sh
    skip_cleanup: true
after_success:
  - if [[ $TEST_SUITE = "{'browsers':['PhantomJS'],'runNegTests':true,'runSimpleTests':true}" ]]; then bash <(curl -s https://codecov.io/bash); fi
